body:
  - type: input
    id: test-input
    attributes:
      label: Test Input
      description: "This is a test description."
      placeholder: "e.g., Test"
    validations:
      required: true
