name: Bug Report
title: "[BUG] "
labels: ["kind/bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out the bug report. Please provide as much information as possible to help us understand and replicate the bug."

  - type: input
    id: openim-server-version
    attributes:
      label: OpenIM Server Version
      description: "Please provide the version number of OpenIM Server you are using."
      placeholder: "e.g., 3.7.1"
    validations:
      required: true
