name: Simple Bug Report
title: "[SIMPLE BUG] "
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: "This is a test to identify template issues."
  - type: input
    id: test-input
    attributes:
      label: Test Input
      description: "Please provide any input here."
      placeholder: "Type something..."
    validations:
      required: true
